from tkinter import *
root=Tk()
root.geometry('300x300')
root.title("My Window")
menubar=Menu(root)
file=Menu(menubar,tearoff=0)
menubar.add_cascade(label='File',menu=file)
file.add_command(label='New File')
file.add_command(label='Open')
file.add_command(label='Save')
file.add_command(label='Save As')
edit=Menu(menubar,tearoff=0)
menubar.add_cascade(label='Edit',menu=edit)
edit.add_command(label='Copy')
edit.add_command(label='Cut')
edit.add_command(label='Paste')
edit.add_command(label='Select All')
root.configure(menu=menubar)
root.mainloop()
